services:
  indoor-nav:
    container_name: indoor-nav
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      network: host
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - navNet
  postgres:
    image: postgis/postgis:18-3.6
    platform: linux/amd64
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - navNet

volumes:
  postgres-data:
    driver: local

networks:
  navNet:
    driver: bridge
