/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiDemoRouteImport } from './routes/ui-demo'
import { Route as TestImportRouteImport } from './routes/test-import'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CalibrateFloorRouteImport } from './routes/calibrate-floor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UiDemoRoute = UiDemoRouteImport.update({
  id: '/ui-demo',
  path: '/ui-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const TestImportRoute = TestImportRouteImport.update({
  id: '/test-import',
  path: '/test-import',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CalibrateFloorRoute = CalibrateFloorRouteImport.update({
  id: '/calibrate-floor',
  path: '/calibrate-floor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calibrate-floor': typeof CalibrateFloorRoute
  '/login': typeof LoginRoute
  '/test-import': typeof TestImportRoute
  '/ui-demo': typeof UiDemoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calibrate-floor': typeof CalibrateFloorRoute
  '/login': typeof LoginRoute
  '/test-import': typeof TestImportRoute
  '/ui-demo': typeof UiDemoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calibrate-floor': typeof CalibrateFloorRoute
  '/login': typeof LoginRoute
  '/test-import': typeof TestImportRoute
  '/ui-demo': typeof UiDemoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calibrate-floor'
    | '/login'
    | '/test-import'
    | '/ui-demo'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calibrate-floor'
    | '/login'
    | '/test-import'
    | '/ui-demo'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/calibrate-floor'
    | '/login'
    | '/test-import'
    | '/ui-demo'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalibrateFloorRoute: typeof CalibrateFloorRoute
  LoginRoute: typeof LoginRoute
  TestImportRoute: typeof TestImportRoute
  UiDemoRoute: typeof UiDemoRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui-demo': {
      id: '/ui-demo'
      path: '/ui-demo'
      fullPath: '/ui-demo'
      preLoaderRoute: typeof UiDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-import': {
      id: '/test-import'
      path: '/test-import'
      fullPath: '/test-import'
      preLoaderRoute: typeof TestImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calibrate-floor': {
      id: '/calibrate-floor'
      path: '/calibrate-floor'
      fullPath: '/calibrate-floor'
      preLoaderRoute: typeof CalibrateFloorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalibrateFloorRoute: CalibrateFloorRoute,
  LoginRoute: LoginRoute,
  TestImportRoute: TestImportRoute,
  UiDemoRoute: UiDemoRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
