/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
<<<<<<< HEAD
<<<<<<< HEAD
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
=======
import { Route as TestImportRouteImport } from './routes/testImport'
=======
import { Route as TestImportRouteImport } from './routes/test-import'
>>>>>>> fe6f833 (Fixed ci errors)
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TestImportRoute = TestImportRouteImport.update({
<<<<<<< HEAD
  id: '/testImport',
  path: '/testImport',
>>>>>>> 4a81322 (made uploade image form)
=======
  id: '/test-import',
  path: '/test-import',
>>>>>>> fe6f833 (Fixed ci errors)
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
<<<<<<< HEAD
<<<<<<< HEAD
  '/login': typeof LoginRoute
=======
  '/testImport': typeof TestImportRoute
>>>>>>> 4a81322 (made uploade image form)
=======
  '/test-import': typeof TestImportRoute
>>>>>>> fe6f833 (Fixed ci errors)
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
<<<<<<< HEAD
<<<<<<< HEAD
  '/login': typeof LoginRoute
=======
  '/testImport': typeof TestImportRoute
>>>>>>> 4a81322 (made uploade image form)
=======
  '/test-import': typeof TestImportRoute
>>>>>>> fe6f833 (Fixed ci errors)
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
<<<<<<< HEAD
<<<<<<< HEAD
  '/login': typeof LoginRoute
=======
  '/testImport': typeof TestImportRoute
>>>>>>> 4a81322 (made uploade image form)
=======
  '/test-import': typeof TestImportRoute
>>>>>>> fe6f833 (Fixed ci errors)
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
<<<<<<< HEAD
<<<<<<< HEAD
  fullPaths: '/' | '/login' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/api/auth/$'
  id: '__root__' | '/' | '/login' | '/api/auth/$'
=======
  fullPaths: '/' | '/testImport' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/testImport' | '/api/auth/$'
  id: '__root__' | '/' | '/testImport' | '/api/auth/$'
>>>>>>> 4a81322 (made uploade image form)
=======
  fullPaths: '/' | '/test-import' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test-import' | '/api/auth/$'
  id: '__root__' | '/' | '/test-import' | '/api/auth/$'
>>>>>>> fe6f833 (Fixed ci errors)
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
<<<<<<< HEAD
  LoginRoute: typeof LoginRoute
=======
  TestImportRoute: typeof TestImportRoute
>>>>>>> 4a81322 (made uploade image form)
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
<<<<<<< HEAD
<<<<<<< HEAD
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
=======
    '/testImport': {
      id: '/testImport'
      path: '/testImport'
      fullPath: '/testImport'
=======
    '/test-import': {
      id: '/test-import'
      path: '/test-import'
      fullPath: '/test-import'
>>>>>>> fe6f833 (Fixed ci errors)
      preLoaderRoute: typeof TestImportRouteImport
>>>>>>> 4a81322 (made uploade image form)
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
<<<<<<< HEAD
  LoginRoute: LoginRoute,
=======
  TestImportRoute: TestImportRoute,
>>>>>>> 4a81322 (made uploade image form)
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
